### ISSUE TITLE
isSingle

### ISSUE THREAD

**Issue by Yu-an** [LSC-MEM-course/random-effect-simulation-assignment-1-Yu-an#1]
Hi,
When I'm running a mixed-effect model on my data, and it gave me a warning isSingle; I read the explanation but I'm still not sure what to do. Does it mean the data does not vary enough for a MEM?
Thanks!
Yu'an

**Comment by scottrjackson** [comment]
check the summary and look for any parameters (particularly random effects) that are estimated to be exactly zero.  Then do some descriptive summaries, plots, etc. to see if you can understand why that might be the case.  It's not necessarily a problem, but it does indicate that dropping whatever effect is estimated to be zero is probably a good idea.  But it's important to try to understand why it's zero!

**Comment by scottrjackson** [comment]
yep, that plot of yours tells a lot of the story, but not all of it.  Here's a quick summary that should help you explain why the estimated variance of a random intercept by test number is 0:

`yy_data %>% group_by(test_number) %>% summarize(N = n(), mean_yn = mean(yn))`

Remember, a random intercept basically says "we expect there to be a baseline difference in responses for different test numbers".

But more generally, your data is very "black and white" in many ways.  But I think more on the topic of random effects, try the code below.  Basically there is no variation at all in the adults. 

`yy_data %>% filter(age_group == "0") %>% group_by(dou) %>% summarize(N = n(), mean_yn = mean(yn))`

So trying to estimate effects for them is a little silly, in the sense of unnecessary.  But for the kids, you are seeing some not-quite 100% behavior in the condition where the adults are all 100%.  But summaries of average % response collapsed across people can always obscure the distinction between two possibilities.  One is that kids are kind of variable, and most kids are around the 80% range, with some variation around that.  This would be consistent with a random effect as discussed in the tutorial.

But look at this plot:

```
children <- yy_data %>% filter(age_group == "1") %>% group_by(participant, dou) %>% summarize(N = n(), mean_yn = mean(yn))
ggplot(children, aes(mean_yn)) + geom_bar() + facet_wrap(~ dou)

```

That is a different situation :-)

**Comment by Yu-an** [comment]
So in these black and white situations, what would be the best way to report this data? I'm a little confused especially because my hypothesis specifically targets whether there is a difference between adults and kids, but I'm not sure if we can safely conclude so here. 
Sorry if you've covered this question in your material! I'm still trying to go through it.

**Comment by scottrjackson** [comment]
We'll talk more in depth about making inferences later, so that will be a good time to discuss what to do with data like this.  The focus right now is on structuring random effects, which is why I'm pushing the questions I am :-)

There are basically two questions I'd suggest you think about, which we can further discuss today.  One is the isSingular issue you started asking about.  Namely, I want you to understand i) why you're getting the warning, ii) what exactly it refers to, iii) how to go about deciding what to do about it, and iv) what you should do about it here.

The second issue is the question of random effect(s) by subject, particularly on the kids.  Namely, does the conception of what a random effect look like fit the apparent pattern in your data?  If so or if not, how?

Both would be good issues to raise during class today :-)

**Comment by Yu-an** [comment]
Thanks!!
